apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: retail-store-istio
  namespace: istio-system
spec:
  profile: default
  
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    enableAutoMtls: true
    defaultConfig:
      tracing:
        zipkin:
          address: jaeger-collector.observability:9411
      
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    
    extensionProviders:
      - name: otel
        opentelemetry:
          service: opentelemetry-collector.observability.svc.cluster.local
          port: 4317

  components:
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 2048Mi
          limits:
            cpu: 1000m
            memory: 4096Mi
        hpaSpec:
          minReplicas: 2
          maxReplicas: 5
          metrics:
            - type: Resource
              resource:
                name: cpu
                target:
                  type: Utilization
                  averageUtilization: 80
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 1024Mi
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
              service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          hpaSpec:
            minReplicas: 2
            maxReplicas: 10
    egressGateways:
      - name: istio-egressgateway
        enabled: true
        k8s:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

  values:
    global:
      mtls:
        enabled: true
      pilotCertProvider: istiod
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        concurrency: 2
    pilot:
      autoscaleEnabled: true
      enableProtocolSniffingForOutbound: true
      enableProtocolSniffingForInbound: true
