apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    network-policy: enabled
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: staging-default-deny-all
  namespace: staging
  labels:
    app.kubernetes.io/name: default-deny
    policy-type: baseline
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
    network-policy: enabled
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: production-default-deny-all
  namespace: production
  labels:
    app.kubernetes.io/name: default-deny
    policy-type: baseline
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-default-deny-all
  namespace: monitoring
  labels:
    app.kubernetes.io/name: default-deny
    policy-type: baseline
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-default-deny-all
  namespace: database
  labels:
    app.kubernetes.io/name: default-deny
    policy-type: baseline
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-default-deny-all
  namespace: redis
  labels:
    app.kubernetes.io/name: default-deny
    policy-type: baseline
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-default-deny-all
  namespace: kafka
  labels:
    app.kubernetes.io/name: default-deny
    policy-type: baseline
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: observability-default-deny-all
  namespace: observability
  labels:
    app.kubernetes.io/name: default-deny
    policy-type: baseline
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ingress-nginx-default-deny-all
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: default-deny
    policy-type: baseline
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
