apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ui-pdb
  namespace: retail-store-production
  labels:
    app.kubernetes.io/name: ui
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: ui
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: catalog-pdb
  namespace: retail-store-production
  labels:
    app.kubernetes.io/name: catalog
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cart-pdb
  namespace: retail-store-production
  labels:
    app.kubernetes.io/name: cart
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cart
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: orders-pdb
  namespace: retail-store-production
  labels:
    app.kubernetes.io/name: orders
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: checkout-pdb
  namespace: retail-store-production
  labels:
    app.kubernetes.io/name: checkout
spec:
  minAvailable: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: checkout
