apiVersion: v1
kind: Secret
metadata:
  name: retail-store-secrets
  namespace: retail-store-staging
type: Opaque
stringData:
  DB_PASSWORD: "change-me-in-production"
  REDIS_PASSWORD: "change-me-in-production"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: retail-store-aws-secrets
  namespace: retail-store-staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: retail-store-aws-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: retail-store/staging/database
        property: password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: retail-store/staging/redis
        property: password
